### ISSUE TITLE
Stolen

### ISSUE THREAD

**Issue by Jude-Gideon** [P-DennyGamingYT/Blooket-Hacks#1]
All stolen from [gliz](https://github.com/therealgliz/blooket-hack/) none of the code works and you just removed the footer.

**Comment by P-DennyGamingYT** [comment]
I gave credit to him and said that I would update all of it since he isn't updating it anymore. Half the stuff is broken and I need to fix it. Ex. all of the "global" files. I also said that I would add in all of the NEW gamemodes. If you could read that might help.

**Comment by Jude-Gideon** [comment]
These scripts are not worth it to fix, if I were you I would makr your own, these need so much work and have a lot of useless code in them.

**Comment by Jude-Gideon** [comment]
Also, none of the API links are valid either.

**Comment by Jude-Gideon** [comment]
Bro, why are you stealing rx's code read his license.

**Comment by nightclubs** [comment]
Greetings, @Jude-Gideon. I see where you're coming from now. I see that @P-DennyGamingYT has credited the authors. But please be assured that if the authors truly cared, they would raise an issue. Let's not get too far ahead of ourselves with Blooket Hacks, and happy coding!, sincerely zt.

**Comment by Jude-Gideon** [comment]
> Greetings, @Jude-Gideon. I see where you're coming from now. I see that @P-DennyGamingYT has credited the authors. But please be assured that if the authors truly cared, they would raise an issue. Let's not get too far ahead of ourselves with Blooket Hacks, and happy coding!, sincerely zt.

Read rx's license it doesn't matter that he credited him.

**Comment by nightclubs** [comment]
> > Greetings, @Jude-Gideon. I see where you're coming from now. I see that @P-DennyGamingYT has credited the authors. But please be assured that if the authors truly cared, they would raise an issue. Let's not get too far ahead of ourselves with Blooket Hacks, and happy coding!, sincerely zt.
> 
> Read rx's license it doesn't matter that he credited him.

I do not know rx, please send his github I shall look.

**Comment by nightclubs** [comment]
> @nightclubs
> 
> https://github.com/rxzyx/Blooket-Hacks/blob/main/LICENSE

That is not a real license, so it has no bearing on anything; it is simply a poorly written license by @rxzyx himself; his license is useless unless he has it under a real license, such as Apache. And because this isn't a real license, he has no right to remove other people's repos, even if it's his own reposted with or without credit.

**Comment by rxzyx** [comment]
> > @nightclubs
> > https://github.com/rxzyx/Blooket-Hacks/blob/main/LICENSE
> 
> That is not a real license, so it has no bearing on anything; it is simply a poorly written license by @rxzyx himself; his license is useless unless he has it under a real license, such as Apache. And because this isn't a real license, he has no right to remove other people's repos, even if it's his own reposted with or without credit.

I regret to inform you that this is but *misinformation*, It is completley legal in doing so: 'within your rights to create a purpose-specific license'. Oh, and 'poorly written' -- we aren't describing your code are we now? Maybe you should do your research before making blatantly biased comments Mr. Johnny Law. Oh, and here is an example: [Facebook Nuclide](https://github.com/facebookarchive/nuclide/blob/master/LICENSE).

**Comment by rxzyx** [comment]
^ If this were not the case, then Facebook's Nuclide would be non-existant.

**Comment by rxzyx** [comment]
Also, Github's DMCA file form clearly asks this question: 'Is the work licensed under an open source license? If so, which open source license? Are the allegedly infringing files being used under the open source license, or are they in violation of the license?', which means that you are allowed to have non-open source license. Incase this is not enough proof, here is an example of a Facebook agent filing a DMCA Takedown over a license-breaking case where people included the code of Facebook's Login page in their code (This was accepted): [Takedown](https://github.com/github/dmca/blob/master/2021/08/2021-08-26-facebook.md). There are various more examples of this: [Search Results](https://github.com/github/dmca/search?q=not+open+source)

**Comment by Jude-Gideon** [comment]
> Also, Github's DMCA file form clearly asks this question: 'Is the work licensed under an open source license? If so, which open source license? Are the allegedly infringing files being used under the open source license, or are they in violation of the license?', which means that you are allowed to have non-open source license. Incase this is not enough proof, here is an example of a Facebook agent filing a DMCA Takedown over a license-breaking case where people included the code of Facebook's Login page in their code (This was accepted): [Takedown](https://github.com/github/dmca/blob/master/2021/08/2021-08-26-facebook.md). There are various more examples of this: [Search Results](https://github.com/github/dmca/search?q=not+open+source)

LMAO Proved him wrong, let me know how the DMCA goes.

**Comment by P-DennyGamingYT** [comment]
@Jude-Gideon finally someone agrees that he has no valid copyright registration. Lol

**Comment by rxzyx** [comment]
Translation: “Finally someone agrees with my unlawful actions that I have to put in measure in order to secure my depressing social needs. Thanks for being a zany.”

**Comment by nightclubs** [comment]
> Translation: “Finally someone agrees with my unlawful actions that I have to put in measure in order to secure my depressing social needs. Thanks for being a zany.”

My point is that I doubt you'll be able to successfully copyright a repository that promotes hacks for another site that strictly prohibits any form of cheating. But hey if it works I'll be surprised tbh that would be a first for me.

**Comment by P-DennyGamingYT** [comment]
Bruh pot meat kettle. Filing a DMCA without copyright registration is illegal. It’s also to claim that your work is copyrighted when it’s not. “ You will have to register, however, if you wish to bring a lawsuit for infringement of a U.S. work.”(United States Copyright Office). Lol

**Comment by nightclubs** [comment]
> Bruh pot meat kettle. Filing a DMCA without copyright registration is illegal. It’s also to claim that your work is copyrighted when it’s not. “ You will have to register, however, if you wish to bring a lawsuit for infringement of a U.S. work.”(United States Copyright Office). Lol

It's all good. He banned me from the server for no reason because all I was doing was talking to his members.

**Comment by rxzyx** [comment]
You lot are really square peg’s in a round hole for this platform. Relying on ‘proof’ that has no correlation whatsoever (which you search hither and thither for). You can keep replying in this circus because I won’t even bother, just know, you were banned for continued misinformation, and to the infringer: ‘ If you are a software designer or developer, you create copyrighted content every day. If someone else is using your copyrighted content in an unauthorized manner on GitHub, you can send us a DMCA takedown notice to request that the infringing content be changed or removed.’ This is from Github itself. You replying to this statement will just show how inept you are even though there is an entire mountain of crucial evidence, adios.

**Comment by nightclubs** [comment]
> You lot are really square peg’s in a round hole for this platform. Relying on ‘proof’ that has no correlation whatsoever (which you search hither and thither for). You can keep replying in this circus because I won’t even bother, just know, you were banned for continued misinformation, and to the infringer: ‘ If you are a software designer or developer, you create copyrighted content every day. If someone else is using your copyrighted content in an unauthorized manner on GitHub, you can send us a DMCA takedown notice to request that the infringing content be changed or removed.’ This is from Github itself. You replying to this statement will just show how inept you are even though there is an entire mountain of crucial evidence, adios.

In your server, you say I was backing up @P-DennyGamingYT, but I wasn't. I was simply stating that I doubted github would remove the repo and that it wasn't worth it to fight over Blooket Cheats.

**Comment by nightclubs** [comment]
> Greetings, @Jude-Gideon. I see where you're coming from now. I see that @P-DennyGamingYT has credited the authors. But please be assured that if the authors truly cared, they would raise an issue. Let's not get too far ahead of ourselves with Blooket Hacks, and happy coding!, sincerely zt.

Let me paraphrase what I said. ```Hello, @Jude-Gideon. I understand where you're coming from now. I see @P-DennyGamingYT has given credit to the authors. Please be assured, however, that if the authors truly cared, they would raise a concern. Let's not get too far ahead of ourselves with Blooket Hacks, and happy coding!, best wishes, zt``` I was incorrect when I stated, "If the authors truly cared, they would raise an issue." As you have raised an issue, this was not supporting anyone. I just noticed this issue between @Jude-Gideon and @P-DennyGamingYT and attempted to resolve it with a simple message. But June refused to give up and persisted with the issue, bringing up your LICENSE, which I checked. Yes, I said it was poorly written, but it complies with github's DMCA. I may have been incorrect in some areas, but let's move on and let @P-DennyGamingYT remove the repo to avoid further complications.

**Comment by rxzyx** [comment]
Ладно. I’ll unban you from my server - you can rejoin if you want. Just try not to be too ‘reactive’.

**Comment by P-DennyGamingYT** [comment]
Bruh, idk why y’all are so mad ok. I’m not taking credit for anything that you made. You can’t do anything about it and it’s a stupid argument. So can we all just please leave it alone. There is nothing that will come from arguing.

**Comment by Jude-Gideon** [comment]
> Bruh, idk why y’all are so mad ok. I’m not taking credit for anything that you made. You can’t do anything about it and it’s a stupid argument. So can we all just please leave it alone. There is nothing that will come from arguing.

Are you stupid or some shit? Read rxzyx's [license](https://github.com/rxzyx/Blooket-Hacks/blob/main/LICENSE) it clearly says no matter what you can't copy the code, it doesn't fucking matter if you credit him at the very bottom of the repo where absolutely nobody will go.

**Comment by P-DennyGamingYT** [comment]
Well if he has copyright registration papers then he could show me. But he isn’t showing me so I don’t have to do anything. If he wants to risk creating a DMCA with fake copyright then he can go ahead.

**Comment by Jude-Gideon** [comment]
> Well if he has copyright registration papers then he could show me. But he isn’t showing me so I don’t have to do anything. If he wants to risk creating a DMCA with fake copyright then he can go ahead.

Read the fucking Github DMCA guidelines, @nightclubs who was on your side even said "Yes, I said it was poorly written, but it complies with github's DMCA. I may have been incorrect in some areas, but let's move on and let @P-DennyGamingYT remove the repo to avoid further complications." his license can take you the fuck down, just take it down to avoid a big mess, it doesn't matter if it's poorly written or not registered it complies with guidelines.
